version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: flexy-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=product
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "3006:3306"

    webserver:
      image: nginx:alpine
      container_name: flexy-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: flexy-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    
    composer:
      image: composer:1.9
      command: ["composer", "install"]
      volumes:
       - /var/www/docker-study.loc/recipe-05/php:/app
